# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-07 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2020, 4, 7, 16, 41, 10, 458658, tzinfo=utc))),
            ],
        ),
    ]
