# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-07 18:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200407_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='datetime',
        ),
        migrations.AddField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 7, 18, 31, 53, 571780, tzinfo=utc)),
        ),
    ]
