# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-11 13:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200408_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=80)),
                ('image', models.ImageField(upload_to='/catagory/')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2020, 4, 11, 13, 29, 44, 394943, tzinfo=utc))),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Blog_Catagory'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 13, 29, 44, 390944, tzinfo=utc)),
        ),
    ]
