# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-11 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200411_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 13, 59, 9, 251847, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blog_catagory',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 13, 59, 9, 254824, tzinfo=utc)),
        ),
    ]
