# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-11 14:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200411_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 14, 59, 23, 573260, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blog_catagory',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 14, 59, 23, 575260, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blog_catagory',
            name='image',
            field=models.ImageField(upload_to='catagory/'),
        ),
    ]
