# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-04-11 17:45
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200411_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 17, 45, 39, 968672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='blog_catagory',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 17, 45, 39, 970668, tzinfo=utc)),
        ),
    ]
